#ingress values
ingress:
  enabled: true
  name: api-gateway
  className: alb
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
  rules:
    - paths:
        - path: /api
          pathType: Prefix
          serviceSuffix: application
          servicePort: 80
        - path: /
          pathType: Prefix
          serviceSuffix: frontend
          servicePort: 80

#backend values
backend:
  replicaCount: 2

  image:
    repository: ilay906/quiz-ai-backend
    tag: latest
    pullPolicy: Always

  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 8000
    annotations: {}

  containerPort: 8000

  envFromSecrets:
    - app-env  

  env:
    - name: MYSQL_SSL_CA
      value: /etc/mysql/ssl/ca.pem

  mysqlCaSecret:
    enabled: true
    name: mysql-ca
    key: ca.pem
    mountPath: /etc/mysql/ssl
    mode: 256  
  resources:
    requests:
      memory: "128Mi"
      cpu: "256m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  livenessProbe:
    enabled: true
    path: /api/health
    portName: http
    initialDelaySeconds: 20
    periodSeconds: 10

  readinessProbe:
    enabled: true
    path: /api/health
    portName: http
    initialDelaySeconds: 5
    periodSeconds: 10

  lifecycle:
    preStopSleepSeconds: 10

  imagePullSecrets: []   
  nodeSelector: {}
  tolerations: []
  affinity: {}

  extraVolumeMounts: []
  extraVolumes: []
  



frontend:
  replicaCount: 1

  image:
    repository: ilay906/quiz-ai-frontend
    tag: "1.0.1"
    pullPolicy: IfNotPresent

  containerPort: 80

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  resources:
    requests:
      memory: "128Mi"
      cpu: "256m"
    limits:
      memory: "256Mi"
      cpu: "512m"

  podLabels: {}
  podAnnotations: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

  lifecycle:
    preStopSleepSeconds: 10

  livenessProbe:
    enabled: false
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10

  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 80
    annotations: {}
    labels: {}