environment: staging
namespace: app-stage

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: ""  # Will use NLB hostname
      paths:
        - path: /stage/api
          pathType: Prefix
          backend:
            service:
              name: quiz-ai-backend
              port:
                number: 80
        - path: /stage
          pathType: Prefix
          backend:
            service:
              name: quiz-ai-frontend
              port:
                number: 80
#backend values
backend:
  replicaCount: 1

  image:
    repository: 505825010815.dkr.ecr.eu-central-1.amazonaws.com/quiz-ai-backend
    tag: latest
    pullPolicy: Always

  nameOverride: "backend"
  fullnameOverride: "quiz-ai-backend"

  podAnnotations: {}
  podLabels: {}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 8000
    annotations: {}

  containerPort: 8000

  envFromSecrets:
    - app-env  

  env:
    - name: MYSQL_SSL_CA
      value: /etc/mysql/ssl/ca.pem
    - name: MYSQL_CA_PATH
      value: /etc/mysql/ssl/ca.pem

  mysqlCaSecret:
    enabled: true
    name: mysql-ca
    key: ca.pem
    mountPath: /etc/mysql/ssl
    mode: 256  
  resources:
    requests:
      memory: "128Mi"
      cpu: "256m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  livenessProbe:
    enabled: true
    path: /api/health
    portName: http
    initialDelaySeconds: 20
    periodSeconds: 10

  readinessProbe:
    enabled: true
    path: /api/health
    portName: http
    initialDelaySeconds: 5
    periodSeconds: 10

  lifecycle:
    preStopSleepSeconds: 10

  imagePullSecrets: []   
  nodeSelector: {}
  tolerations: []
  affinity: {}

  extraVolumeMounts: []
  extraVolumes: []
  



frontend:
  replicaCount: 1

  image:
    repository: 505825010815.dkr.ecr.eu-central-1.amazonaws.com/quiz-ai-frontend
    tag: latest
    pullPolicy: Always

  nameOverride: "frontend"
  fullnameOverride: "quiz-ai-frontend"

  containerPort: 80

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  resources:
    requests:
      memory: "128Mi"
      cpu: "256m"
    limits:
      memory: "256Mi"
      cpu: "512m"

  podLabels: {}
  podAnnotations: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

  lifecycle:
    preStopSleepSeconds: 10

  livenessProbe:
    enabled: false
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10

  readinessProbe:
    enabled: true
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10

  service:
    enabled: true
    type: ClusterIP
    port: 80
    targetPort: 80
    annotations: {}
    labels: {}