apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz-ai-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # After External Secrets config
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz-ai-prod 
  source:
    repoURL: https://github.com/Ilay1214/quiz_ai_infra
    targetRevision: main
    path: infra/quiz-ai-helm
    helm:
      releaseName: quiz-ai  
      valueFiles:
        - production_values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true  
