apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: app-env
  namespace: app-dev
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: app-env
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: prod/quiz-ai
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: mysql-ca
  namespace: app-dev
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: mysql-ca
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ca.pem
      remoteRef:
        key: prod/quiz-ai
        property: MYSQL_SSL_CA
