apiVersion: v1
kind: Namespace
metadata:
  name: app-stage
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-env
  namespace: app-stage
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: app-env
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: stage/quiz-ai
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-ca
  namespace: app-stage
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: mysql-ca
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ca.pem
      remoteRef:
        key: stage/quiz-ai
        property: MYSQL_SSL_CA
